config.code=232323
config.username=jonas
config.message=Hola que tal como estas áéññ
config.listOfValues=hola,que,tal,como,estas,hoy
config.valuesMap={product: 'cpu Intel Core i7 12th', description: 'Alder Lake, 12 Core, a 5GHz', price: '1000'}